### ISSUE TITLE
How is this collection of packages intended to be used?

### ISSUE THREAD

**Issue by sstadick** [JuliaString/Strs.jl#121]
Hello!

This seems like a great collection of utilities to fill the gap in the standard library, but I can't figure out how you intended for it to be used? Is `Strs.jl` the top level package to add, or is `StrAPI.jl` the one to use? Is there any module level documentation? Poking around on juliahub I wasn't seeing anything in the Strs or StrAPI packages. Are there any examples anywhere?

Also, the website link just redirects to the Github org page: http://juliastring.org/.

Lastly, I see this roadmap from 2018: https://github.com/JuliaString/Strs.jl/issues/97, with no updates. Is this set of packages still under active development or in maintenance only mode? (In other words, do you want big PRs that change APIs, or should these be forked?)

**Comment by ScottPJones** [comment]
It is still under active development.

Strs.jl is a convenience package, with all of the separate pieces pulled together.

Some parts can be used separately (or combined), such as StrLiterals, StrFormat, StrEntities.

Also, some of the lower-level pieces (such as CharSetEncodings & ChrBase) could be used to help implement other string types.

JuliaString.org is not just for the Str* packages, but also others, such as ShortStrings.jl and InternedStrings.jl.
I want it to be the home of good string related Julia packages.

What sort of changes to APIs were you thinking of?
Mostly, I've followed the implicit interface for AbstractString, as defined in Julia Base.

**Comment by sstadick** [comment]
Thanks for the reply! What I was originally having a hard time with was just figuring out how to use these libraries as someone new to Julia and disappointed by the stdlib String support. I've moved off Julia for the time being, but hope to come back to it at some point. 

Some high level examples / links to documentation of expected use cases would be super helpful for new people. 👍
