### ISSUE TITLE
slow hash of custom string types

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#48]
Currently `hash` for custom strings falls back to `hash` of `String` which is painfully slow.
This is a crucial thing to fix if we want dictionaries or sets work fast with `Str`-family.
Of course we should ensure that we return the same hash values (which might be hard - I have not thought about it in detail).

**Comment by ScottPJones** [comment]
Ha, I just noticed the same problem, should have read all of your issues right away!

**Comment by ScottPJones** [comment]
#72 partially solves this.  A number of the Str types now directly call the `memhash` function that Julia uses, and optimized conversions are used for now on the rest.
There does seem (to me at least) to be a major problem with the way that `hash(a * b)` is not equal to `hash(b, hash(a))`, something that is necessary for performing hashing in chunks (if you have something that won't fit in memory that you need to hash, for example), or for improving the performance of hashing non-UTF8 compatible strings such as Latin strings by hashing substrings where the letters are all ASCII.

That should probably be brought up as an issue.

**Comment by ScottPJones** [comment]
I believe that with #77, this can be closed.
I think this would actually be useful to get into base, and replace the current C Murmurhash3 code with my Julia version, which is faster, and has the optimized way of making a UTF-8 compatible hash for any AbstractString.

**Comment by bkamins** [comment]
works nice :).
