### ISSUE TITLE
Conversions between Char and Strs.CodePoint

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#51]
Currently direct conversions between `Char` and `Strs.CodePoint` concrete types seem not to be supported both ways (you have to go through `UInt32` in the middle). Is this intentional?

**Comment by ScottPJones** [comment]
That should be fixed in the update I've been working on for the last week or so.
I hopefully will be able to push it tonight.

**Comment by ScottPJones** [comment]
Should be fixed now (#52), please close if it works for you now.

**Comment by bkamins** [comment]
fixed
