### ISSUE TITLE
UniStr type performance

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#54]
I like `UniStr` type. I have small performance issues with it.

First is benchmarking:
* do benchmarks really show that union of 4 types on 0.7 can be actually considered small 😄 (I know 2 is small but not have seen benchmarks for 4)
* actually this union might be 5 not 4 - how does it behave then: `Union{UniStr, Missing}` and `Union{UniStr, Nothing}`

The second is broadcasting and mapping. The compiler does not properly detect the required Union-type:
```
julia> UniStr.(["a","ą","∀"])
3-element Array{Strs.Str{T,Void,Void,Void} where T,1}:
 "a"
 "ą"
 "∀"

julia> map(UniStr, ["a","ą","∀"])
3-element Array{Strs.Str{T,Void,Void,Void} where T,1}:
 "a"
 "ą"
 "∀"

julia> UniStr[UniStr(s) for s in ["a","ą","∀"]]
3-element Array{UniStr,1}:
 "a"
 "ą"
 "∀"
```

Any thoughts of fixing it (maybe some promotion rules should be added). Additionally such promotion rules should take `Missing` into account (but maybe this will be handled automatically on 0.7).

Interestingly `Set` works correctly:

```
julia> Set{UniStr}(UniStr[UniStr(s) for s in ["a","ą","∀"]])
Set(Union{ASCIIStr, _LatinStr, _UCS2Str, _UTF32Str}["ą", "a", "∀"])

julia> Set{UniStr}(UniStr.(["a","ą","∀"]))
Set(Union{ASCIIStr, _LatinStr, _UCS2Str, _UTF32Str}["ą", "a", "∀"])
```
(although the type signature is lost)

**Comment by ScottPJones** [comment]
> (although the type signature is lost)
That may just be a display issue.
You could check what the eltype is of the Set, and see if it is == UniStr.

**Comment by bkamins** [comment]
I know that it is a display issue only and it is `UniStr` but solving this display issue would be nice (a novice user probably prefers to see `UniStr` signature everywhere, especially as `Union` refers to internal types). So I would leave it open to keep track that it would be nice to solve it some day.

**Comment by ScottPJones** [comment]
I think this may also be a v0.6 vs. master issue.  On master, I get the following:
```julia
julia> f = UniStr["foobar", "\U1f596", "ÿ", "\ufffd"]
4-element Array{UniStr,1}:
 "foobar"
 "🖖"
 "ÿ"
 "�"

julia> typeof(f)
Array{UniStr,1}

julia> eltype(f)
UniStr
```

**Comment by bkamins** [comment]
Yes now on master it is OK, so I would close it.
