### ISSUE TITLE
Make test/bench.jl user independent

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#58]
Currently *test/bench.jl* relies on a concrete user machine configuration, e.g.:
```
const userdir = "/Users/scott/"
```
It would be good to make it runnable without modifying sources in the future.

**Comment by ScottPJones** [comment]
Yes, true - at the top I say it's very much WIP and hardcoded!
Since you (and Stefan) are looking at things now, I'll fix that.
