### ISSUE TITLE
Printing of UniStr

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#59]
Currently on 0.7 and 0.6.2 the following fail to print:
```
UniStr(string(Char(0xb5)))
```
and
```
UniStr(string(Char(0x00010000)))
```

(for different reasons)

**Comment by ScottPJones** [comment]
Both work fine for me, on v0.6.2 and v0.7 (built today), but that may be because of the fixes I just pushed.

**Comment by bkamins** [comment]
Yes your fixes fix it 😄
