### ISSUE TITLE
specialize join and *

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#60]
Currently `join` in base uses `sprint`. We should have a special method for `UniStr` for it.
Similar for `*` which uses `string`.

**Comment by bkamins** [comment]
And additionally general string concatenation (equivalent of `string` function) would be welcome.

**Comment by ScottPJones** [comment]
I do have some string concatenation implemented, but don't have tests yet to make sure that the results are what you'd expect.
When mixing ASCIIStr & UTF8Str & String, one could simply make a string, just copying the bytes.
Mixing ASCIIStr & LatinStr should give LatinStr, ASCII and/or LatinStr and _LatinStr should give _LatinStr.
Mixing ASCIIStr/LatinStr/_LatinStr with String, depending on compile time info may not give the best result.

I believe this is an issue with a lot of Julia development - a lot of effort is put into making things type-stable, when a single type for all cases can be a lot worse than using a Union with run-time heuristics and checks to see what representation is best (esp. when it can be kept to small dispatch tables and doesn't need "full" dynamic dispatch.

For example, if you have a number of byte type strings, but some are potentially incompatible (LatinStr with UTF8Str or String, it can be a lot more efficient to quickly check the strings before copying, to see if a conversions really are necessary - i.e. many Strings are really only ASCII, which can also be true for LatinStr [but not _LatinStr, which is part of the reason for it's existence]).
Probably we need to tell the compiler that the result of mixed concatenations is a UniStr, if there are any String, UTF8Str, UTF16Str in the mix).

One thing to be careful with also, is that substrings of _LatinStr, _UCS2Str, and _UTF32Str might be
LatinStr, UCS2Str, UTF32Str, depending on the contents of the substring.

**Comment by bkamins** [comment]
Yes. From the end-user perspective I would say that:
* experts will welcome 100% what you say and actually use the flexibility
* normal users will want to see `UniStr` everywhere and not care what is underneath and rely on the library to do its magic 😄

Therefore For me the priority would be to make types constituting `UniStr` work as expected as this is the type we can expect normal user to use (as they for sure will not understand the complexities - most of them probably does not know what Unicode or UTF8 is in detail).

**Comment by ScottPJones** [comment]
Yes, precisely.  That is my goal.  Experts can utilize one of the concrete types (`ASCIIStr`, `LatinStr`, `UCS2Str`, etc. for better performance, avoiding even the hopefully very small penalty from small union dispatching, and everybody else will simply use `UniStr`, get much better performance, and not have to worry about the crazy indexing issues with any multi code unit encoding, such as UTF-8, UTF-16, etc., as they do currently.

**Comment by ScottPJones** [comment]
I've added a whole bunch of optimizations for join, and added it to my benchmarking code,
if you care to take a look at the performance.

**Comment by bkamins** [comment]
`*` throws an error when both strings are of the same concrete type:
```
ERROR: MethodError: string(::ASCIIStr, ::ASCIIStr) is ambiguous. Candidates:
  string(collection::Strs.Str{#s21,SubStr,Cache,Hash} where Hash where Cache where SubStr where #s21<:Union{ASCIICSE, LatinCSE, _LatinCSE}...) in Strs
  string(c::Union{#s21, SubString{#s21}} where #s21<:(Strs.Str{ASCIICSE,SubStr,Cache,Hash} where Hash where Cache where SubStr)...) in Strs
Possible fix, define
  string(::Vararg{#s21 where #s21<:(Strs.Str{ASCIICSE,SubStr,Cache,Hash} where Hash where Cache where SubStr),N} where N)
```
(works fine for mixed types)

**Comment by ScottPJones** [comment]
Thanks for catching that one!   Will try to fix soonest.   Dealing with getting correct promotions without causing type piracy or ambigious definitions is not at all easy IMO in Julia.

**Comment by bkamins** [comment]
Yeah avoiding type piracy is the crucial problem in my experience ;).
