### ISSUE TITLE
Julia 0.6.2 compatibility

### ISSUE THREAD

**Issue by bkamins** [JuliaString/Strs.jl#82]
Current master fails to load on Julia 0.6.2 due to problem in line 20 of `src/compat.jl` (missing `Base.SamplerType`).

**Comment by ScottPJones** [comment]
Yes - since you had indicated you were more interested in seeing things working for v0.7, I concentrated on that first, getting the bugs you found fixed.  I'll have things working again on v0.6.2 shortly.  Thanks!

**Comment by bkamins** [comment]
Sure - I am just trying to cover all (and you wanted to support 0.6.2).

**Comment by ScottPJones** [comment]
Fixed by #84!
Took a while because I'd added a bunch of tests from master, not all of which worked on v0.6.2.
